### ISSUE TITLE
Missing "pattern" part of template directory so fails to load template.

### ISSUE THREAD

**Issue by ElPiloto** [cvigilv/esqueleto.nvim#19]
Hello,

Thanks for the plugin!  I get an error when I try to insert a python skeleton.  If I have `...../skeletons/python/test.py` in my skeletons, and `pattern = {'python'}` in my esqueleto config, it throws this error when I try to 

![image](https://user-images.githubusercontent.com/629190/212500589-3d5261fd-f24c-411a-835f-fc2fc27de329.png)

I've isolated it to this line here, which which works when I modify it to include the pattern.
https://github.com/cvigilv/esqueleto.nvim/blob/77640778a7d280f339be703709bae87831f1197c/lua/esqueleto/init.lua#L52

For good measure, here's my exact config:

![image](https://user-images.githubusercontent.com/629190/212500638-403aa1e2-1c1e-4c17-a315-a1688b0dbb0a.png)

Please let me know if there's a bug here or if I've got something misconfigured.  Thanks!

**Comment by cvigilv** [comment]
Thanks for the bug report, will fix in a couple of hours.

**Comment by cvigilv** [comment]
Fixed in release v0.2.1
