### ISSUE TITLE
'Wildcard' is not used correctly

### ISSUE THREAD

**Issue by andrewferrier** [cvigilv/esqueleto.nvim#42]
Hello. Me again! Thanks again for your hard work writing esqueleto.

One small piece of feedback - you might want to reconsider the word 'wildcard'. I'm not sure if you're a native English speaker, but as used in esqueleto and the associated docs, this isn't quite the right word for the concept you're going for, I think. Generally, a wildcard is a card/concept/word which can stand for anything (for example, `*` and `?` in most shells) - that isn't what the wildcards in esqueleto are, if I've understood correctly, they are more like 'placeholders' or (ironically) 'templates'.

It's obviously not a big issue, and I think you explain it clearly in the docs so not a big worry, but if you have the opportunity to change this without breaking existing behaviour, it might be worth considering. Just a thought... I won't be offended if you close this :)

Thanks again for all your hard work on this great plugin!

**Comment by cvigilv** [comment]
Let me give it a thought and I'll add some variation here to discuss. Wildcard comes from common terminology in related plugins.

Thanks for the idea!

**Comment by cvigilv** [comment]
@andrewferrier maybe the "wildcards" could be called "tokens"? I don't like 'placeholders' nor 'templates' (the latter for obvious reasons). I'm not putting this as a priority, but the point you make is true, since a "wildcard" could (eventually) be a wildcard as you describe it.

Let me know what you think

**Comment by cvigilv** [comment]
Closing this issue as it went stale. If discussion around this topic is relevant again, I will open this issue.
