### ISSUE TITLE
Latex filetypes? 

### ISSUE THREAD

**Issue by Kr30x** [cvigilv/esqueleto.nvim#43]
Hello, I'm enjoying using your plugin. However, I'm stuck with creating a LaTeX template. When I need to create a python or cpp template, everything seems fine, but when it comes to LaTeX, I don't know what pattern to use. I tried 'latex', 'tex'. 

My file structure is just like in the set up example (I wanted to put it in here, but something is wrong with indentation it tree :(  ). 

How can I fix this problem or what is the logic behind patterns namings?

**Comment by cvigilv** [comment]
Could you provide an example? I also use LaTeX and have some templates that are triggered by `esqueleto` (see [here](https://github.com/cvigilv/mateo.nvim/tree/098dd4182cf63a5d2d12ed45810e23f142b6906d/skeletons) for examples) defining the pattern as `tex` (see [here](https://github.com/cvigilv/mateo.nvim/blob/098dd4182cf63a5d2d12ed45810e23f142b6906d/lua/mateo/plugin/qol.lua#L30C7-L30C57) for my plugin config).

**Comment by Kr30x** [comment]
I've recorded my screen and uploaded a [video](https://youtu.be/-GOdj4oHOwQ)

**Comment by cvigilv** [comment]
mmm... thats weird... Could you open a `tex` file and type on the command line `set filetype` and copy the output here?

Also, the files MUST BE empty, otherwise it won't work. I wasn't able to see if the file already existed. Maybe try deleting the file first and creating it again to see if it works.

**Comment by cvigilv** [comment]
Saw the video again and noticed something: Your current config sets `tex` file `filetype` to `plaintex`, therefore your current configuration for the plugin won't work. Could you test changing the `tex` pattern for `plaintex` to see if the plugin prompts insertion?

**Comment by Kr30x** [comment]
I've changed to `plaintex` and everything forked as supposed to, thank you!
