### ISSUE TITLE
feat: add optional buf_id param to wildcard

### ISSUE THREAD

**Issue by AgatZan** [cvigilv/esqueleto.nvim#55]
Inspired by [spooky.nvim](https://github.com/Futarimiti/spooky.nvim#:~:text=return%20function%20(-,buf,-)%0A%20%20local%20name%20%3D%20vim)

**Comment by cvigilv** [comment]
This can be easily done adding that wildcard to your config as follows:

~~~lua
reauire("esqueleto").setup({
  -- Your config...
  wildcards = {
    lookup = {
      ["bufid"] = function() vim.api.nvim_get_current_buf() end,
    },
  },
})
~~~

Let me know if this works for your needs, thanks for the issue.
