### ISSUE TITLE
Default template directory naming inconsistent

### ISSUE THREAD

**Issue by itepechi** [cvigilv/esqueleto.nvim#56]
The default template directory name used in this repository has inconsistent singular/plural forms, which can be confusing for new users. Also, I noticed that the commit c019c9a5a710b6a60ca88cbda53c2912ba647f56 [(1)](https://github.com/cvigilv/esqueleto.nvim/commit/c019c9a5a710b6a60ca88cbda53c2912ba647f56#diff-9425e426afda4466d4eb7f08450ac38fa6598fd215883eb8f21f88c378e7e013) was actually a breaking change for users using the default directory name, although it was not marked as such.

### Written in singular

- `doc/esqueleto.txt`: [(1)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/doc/esqueleto.txt#L45), [(2)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/doc/esqueleto.txt#L78)
- `lua/esqueleto/config.lua`: [(1)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/lua/esqueleto/config.lua#L7)

### Written in plural

- `README.md`: [(1)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/README.md?plain=1#L120), [(2)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/README.md?plain=1#L152), [(3)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/README.md?plain=1#L228)
- `doc/esqueleto.txt`: [(1)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/doc/esqueleto.txt#L69), [(2)](https://github.com/cvigilv/esqueleto.nvim/blob/a35c2d1c070403bd2a451f259d57c227d13a2289/doc/esqueleto.txt#L126)
- `skeletons/`: (the directory itself)

**Comment by itepechi** [comment]
At first I thought about submitting a pull request, but honestly I don't know which form we should prefer as I'm not the author of this plugin, so I ended up opening an issue instead.

**Comment by cvigilv** [comment]
Thanks for submitting the issue, I'll correct the spelling on those and submit a breaking change flag so people are aware of this. Thanks for catching this, didn't think of it as a problem on at the moment.

**Comment by cvigilv** [comment]
Maybe I could support both, will see what I can do.
